server:
  port: 8001

# 进阶配置（可选）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false # 建议关闭（避免 LazyInitializationException）
    generate-ddl: false # 禁用自动生成 DDL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      javax.persistence.schema-generation.database.action: none
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        jdbc.time_zone: UTC

